config/routes.rb
Rails.application.routes.draw do

  get 'transactions/new'

  get 'transactions/create'

  

  get 'sessions/new'
  resources :transactions
  resources :users
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'contact' => 'static_pages#contact'
  get 'profile/:id' => 'users#profile', as: :profile
  get 'transaction/index' => 'transactions#index', as: :alltran

  root 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Bank by Johanna</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Big_Bank_Theory", root_path, id: "logo" %>
		<% if logged_in? %>
		<% if current_user.admin? %>
		ADMIN
		<% end %>
		<% end %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li>
					<%= link_to "Home", root_path %>
				</li>
				<% if logged_in? %>
				<li>
					<%= link_to "Users", users_path %>
				</li>
				<li>
					<%= link_to "Settings", edit_user_path(current_user) %>
				</li>
				<li>
					<%= link_to "Profile", profile_path(current_user) %>
				</li>
				<li>
					<%= link_to "All Transactions", alltran_path %>
				</li>
				<li>
					<%= link_to "New transaction", new_transaction_path %>
				</li>
				<li>
					<%= link_to "Log out", logout_path, method: "delete" %>
				</li>

				<% else %>
				<li>
					<%= link_to "Log in", login_path %>
				</li>
				<li>
					<%= link_to "Sign in", new_user_path %>
				</li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Bank</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<div class="container">
			<%= render 'layouts/header' %>
			<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>">
				<%= message %>
			</div>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
		<%= debug(params) if Rails.env.development? %>
	</body>
</html>